= Reasoning about M&S _as a Service_

image:https://img.shields.io/badge/code%20style-black-000000.svg[alt=Code style: black, link=https://github.com/psf/black]
image:https://img.shields.io/badge/%20imports-isort-%231674b1?style=flat&labelColor=ef8336[alt=Imports: isort, link=https://timothycrosley.github.io/isort]

Making models, the ability to simulate them, and the simulation results part of the semantic web requires an ontology that links the real (or envisioned) world in terms of systems, context, initial state, ... to their abstract representations as model instances, input data, initial conditions et cetera and also captures knowledge about the involved concepts. The ontology developed in this repository does just that.


== Competency Questions
Competency questions are used to assess whether or not the developed ontology can fulfil its purpose. They are realized as unit tests, written in Python using the https://docs.pytest.org/en/6.2.x/[pytest] framework. Since the competency questions involve instance retrieval, an ABox is needed; it is populated in `tests/data/individuals.ttl`.

WARNING: At the moment, only relationships explicitly defined in the ABox are found -- so far, there is no reasoner involved in running the unit tests!

.Competency Questions accounted for via unit test
. Given a *class of systems*, ...
.. All models for classes of systems?
.. All models for classes of systems that approximate some quantity Q?
. Given a *system*, ...
.. All known models which can be instantiated to represent a system?
.. All known model instances of a system?
.. _All known dependencies for starting a simulation?_
. Given a *model*, ...
.. All known required parameters for instantiation of a model?
.. All known default parameters of a model?
. Given a *model instance*, ...
.. ...
. Given a *solver*, ...
.. All known required parameters for instantiation of a solver?
.. All known default parameters of a solver?
. Given a *solver instance*, ...
.. ...


.Additional interesting Questions
* Possible to create forecast for system/class of systems?
* Possible to read system state from real-world/envisioned sensor?
* ...
